# Generated by Django 3.2.15 on 2022-09-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20220917_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='updated',
        ),
    ]
