# Generated by Django 3.2.15 on 2022-09-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.attachmenttranscript'),
        ),
    ]
