# Generated by Django 3.2.15 on 2022-09-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20220926_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.factory'),
        ),
    ]
