# Generated by Django 3.2.15 on 2022-09-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
    ]
