# Generated by Django 3.2.15 on 2022-09-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_item_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.size'),
        ),
    ]
