# Generated by Django 3.2.15 on 2022-10-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_item_higher_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.sector'),
        ),
    ]
