# Generated by Django 3.2.15 on 2022-10-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_transaction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.factory'),
        ),
    ]
