# Generated by Django 3.2.15 on 2022-10-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_transaction_factory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='factory',
        ),
    ]
